"""Project to run an sklearn experiment as part of my bachelor's thesis."""
import typing as tp

import benchbuild as bb
from plumbum import local

from varats.utils.config import get_current_config_id

from varats.project.project_domain import ProjectDomains
from varats.paper.paper_config import PaperConfigSpecificGit
from varats.project.project_util import ProjectBinaryWrapper
from varats.project.varats_project import VProject
from varats.utils.git_util import ShortCommitHash
from varats.project.project_util import (
    ProjectBinaryWrapper,
    BinaryType,
    get_local_project_repo,
    verify_binaries,
    RevisionBinaryMap,
)

from benchbuild.command import SourceRoot, WorkloadSet
from varats.experiment.workload_util import (
    RSBinary,
    WorkloadCategory,
    ConfigParams,
)
from varats.project.varats_command import VCommand
from varats.project.sources import FeatureSource


class SklearnProjectSGD(VProject):
    """
    Project to run an sklearn experiment: stochastic gradient descent classifier - sgd.
    """

    NAME = 'sklearn_experiment_sgd'  # Estimator anpassen
    DOMAIN = ProjectDomains.HPC
    GROUP = 'python_projects'
    
    SOURCE = [
        PaperConfigSpecificGit(
            project_name=NAME,
            remote="https://github.com/lukasklein-dev/lk_bachelor_sklearn",
            local="lk_bachelor_sklearn",
            limit=None,
            refspec="origin/HEAD"),
        FeatureSource()
    ]

    WORKLOADS = {
        WorkloadSet(WorkloadCategory.MEDIUM): [
            VCommand(
                SourceRoot("lk_bachelor_sklearn") / RSBinary("case_study_MNIST"),
                "--estimator-sgd", # Estimator anpassen
                ConfigParams(),
            )
        ]
    }

    @staticmethod
    def binaries_for_revision(
            revision: ShortCommitHash) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        binary_map = RevisionBinaryMap(get_local_project_repo(
            SklearnProjectSGD.NAME)) # Estimator anpassen

        binary_map.specify_binary("case_study_MNIST", BinaryType.EXECUTABLE, override_entry_point="case_study_MNIST.py")

        return binary_map[revision]

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        """Compile the project."""
        source = local.path(self.source_of_primary)

        with local.cwd(source):
            verify_binaries(self)


class SklearnProjectKNN(VProject):
    """
    Project to run an sklearn experiment: k-nearest neighbors classifier - knn.
    """

    NAME = 'sklearn_experiment_knn'  # Estimator anpassen
    DOMAIN = ProjectDomains.HPC
    GROUP = 'python_projects'
    
    SOURCE = [
        PaperConfigSpecificGit(
            project_name=NAME,
            remote="https://github.com/lukasklein-dev/lk_bachelor_sklearn",
            local="lk_bachelor_sklearn",
            limit=None,
            refspec="origin/HEAD"),
        FeatureSource()
    ]

    WORKLOADS = {
        WorkloadSet(WorkloadCategory.MEDIUM): [
            VCommand(
                SourceRoot("lk_bachelor_sklearn") / RSBinary("case_study_MNIST"),
                "--estimator-knn", # Estimator anpassen
                ConfigParams(),
            )
        ]
    }

    @staticmethod
    def binaries_for_revision(
            revision: ShortCommitHash) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        binary_map = RevisionBinaryMap(get_local_project_repo(
            SklearnProjectKNN.NAME)) # Estimator anpassen

        binary_map.specify_binary("case_study_MNIST", BinaryType.EXECUTABLE, override_entry_point="case_study_MNIST.py")

        return binary_map[revision]

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        """Compile the project."""
        source = local.path(self.source_of_primary)

        with local.cwd(source):
            verify_binaries(self)


class SklearnProjectSVC(VProject):
    """
    Project to run an sklearn experiment: support vector classifier - svc.
    """

    NAME = 'sklearn_experiment_svc'  # Estimator anpassen
    DOMAIN = ProjectDomains.HPC
    GROUP = 'python_projects'
    
    SOURCE = [
        PaperConfigSpecificGit(
            project_name=NAME,
            remote="https://github.com/lukasklein-dev/lk_bachelor_sklearn",
            local="lk_bachelor_sklearn",
            limit=None,
            refspec="origin/HEAD"),
        FeatureSource()
    ]

    WORKLOADS = {
        WorkloadSet(WorkloadCategory.MEDIUM): [
            VCommand(
                SourceRoot("lk_bachelor_sklearn") / RSBinary("case_study_MNIST"),
                "--estimator-svc", # Estimator anpassen
                ConfigParams(),
            )
        ]
    }

    @staticmethod
    def binaries_for_revision(
            revision: ShortCommitHash) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        binary_map = RevisionBinaryMap(get_local_project_repo(
            SklearnProjectSVC.NAME)) # Estimator anpassen

        binary_map.specify_binary("case_study_MNIST", BinaryType.EXECUTABLE, override_entry_point="case_study_MNIST.py")

        return binary_map[revision]

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        """Compile the project."""
        source = local.path(self.source_of_primary)

        with local.cwd(source):
            verify_binaries(self)


class SklearnProjectRFC(VProject):
    """
    Project to run an sklearn experiment: random forest classifier - rfc.
    """

    NAME = 'sklearn_experiment_rfc'  # Estimator anpassen
    DOMAIN = ProjectDomains.HPC
    GROUP = 'python_projects'
    
    SOURCE = [
        PaperConfigSpecificGit(
            project_name=NAME,
            remote="https://github.com/lukasklein-dev/lk_bachelor_sklearn",
            local="lk_bachelor_sklearn",
            limit=None,
            refspec="origin/HEAD"),
        FeatureSource()
    ]

    WORKLOADS = {
        WorkloadSet(WorkloadCategory.MEDIUM): [
            VCommand(
                SourceRoot("lk_bachelor_sklearn") / RSBinary("case_study_MNIST"),
                "--estimator-rfc", # Estimator anpassen
                ConfigParams(),
            )
        ]
    }

    @staticmethod
    def binaries_for_revision(
            revision: ShortCommitHash) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        binary_map = RevisionBinaryMap(get_local_project_repo(
            SklearnProjectRFC.NAME)) # Estimator anpassen

        binary_map.specify_binary("case_study_MNIST", BinaryType.EXECUTABLE, override_entry_point="case_study_MNIST.py")

        return binary_map[revision]

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        """Compile the project."""
        source = local.path(self.source_of_primary)

        with local.cwd(source):
            verify_binaries(self)


class SklearnProjectBGM(VProject):
    """
    Project to run an sklearn experiment: bayesian gaussian mixture classifier - bgm.
    """

    NAME = 'sklearn_experiment_bgm'  # Estimator anpassen
    DOMAIN = ProjectDomains.HPC
    GROUP = 'python_projects'
    
    SOURCE = [
        PaperConfigSpecificGit(
            project_name=NAME,
            remote="https://github.com/lukasklein-dev/lk_bachelor_sklearn",
            local="lk_bachelor_sklearn",
            limit=None,
            refspec="origin/HEAD"),
        FeatureSource()
    ]

    WORKLOADS = {
        WorkloadSet(WorkloadCategory.MEDIUM): [
            VCommand(
                SourceRoot("lk_bachelor_sklearn") / RSBinary("case_study_MNIST"),
                "--estimator-bgm", # Estimator anpassen
                ConfigParams(),
            )
        ]
    }

    @staticmethod
    def binaries_for_revision(
            revision: ShortCommitHash) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        binary_map = RevisionBinaryMap(get_local_project_repo(
            SklearnProjectBGM.NAME)) # Estimator anpassen

        binary_map.specify_binary("case_study_MNIST", BinaryType.EXECUTABLE, override_entry_point="case_study_MNIST.py")

        return binary_map[revision]

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        """Compile the project."""
        source = local.path(self.source_of_primary)

        with local.cwd(source):
            verify_binaries(self)


class SklearnProjectDTCTest(VProject):
    """
    Project to run an sklearn experiment: decision tree classifier - dtc.
    TEST: only the first two configurations of dtc are run.
    This is used to verify the evaluation pipeline setup.
    """

    NAME = 'sklearn_experiment_dtc_test'  # Estimator anpassen
    DOMAIN = ProjectDomains.HPC
    GROUP = 'python_projects'
    
    SOURCE = [
        PaperConfigSpecificGit(
            project_name=NAME,
            remote="https://github.com/lukasklein-dev/lk_bachelor_sklearn",
            local="lk_bachelor_sklearn",
            limit=None,
            refspec="origin/HEAD"),
        FeatureSource()
    ]

    WORKLOADS = {
        WorkloadSet(WorkloadCategory.MEDIUM): [
            VCommand(
                SourceRoot("lk_bachelor_sklearn") / RSBinary("case_study_MNIST"),
                "--estimator-dtc", # Estimator anpassen
                ConfigParams(),
            )
        ]
    }

    @staticmethod
    def binaries_for_revision(
            revision: ShortCommitHash) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        binary_map = RevisionBinaryMap(get_local_project_repo(
            SklearnProjectDTCTest.NAME)) # Estimator anpassen

        binary_map.specify_binary("case_study_MNIST", BinaryType.EXECUTABLE, override_entry_point="case_study_MNIST.py")

        return binary_map[revision]

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        """Compile the project."""
        source = local.path(self.source_of_primary)

        with local.cwd(source):
            verify_binaries(self)


class SklearnProjectDTC(VProject):
    """
    Project to run an sklearn experiment: decision tree classifier - dtc.
    """

    NAME = 'sklearn_experiment_dtc'  # Estimator anpassen
    DOMAIN = ProjectDomains.HPC
    GROUP = 'python_projects'
    
    SOURCE = [
        PaperConfigSpecificGit(
            project_name=NAME,
            remote="https://github.com/lukasklein-dev/lk_bachelor_sklearn",
            local="lk_bachelor_sklearn",
            limit=None,
            refspec="origin/HEAD"),
        FeatureSource()
    ]

    WORKLOADS = {
        WorkloadSet(WorkloadCategory.MEDIUM): [
            VCommand(
                SourceRoot("lk_bachelor_sklearn") / RSBinary("case_study_MNIST"),
                "--estimator-dtc", # Estimator anpassen
                ConfigParams(),
            )
        ]
    }

    @staticmethod
    def binaries_for_revision(
            revision: ShortCommitHash) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        binary_map = RevisionBinaryMap(get_local_project_repo(
            SklearnProjectDTC.NAME)) # Estimator anpassen

        binary_map.specify_binary("case_study_MNIST", BinaryType.EXECUTABLE, override_entry_point="case_study_MNIST.py")

        return binary_map[revision]

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        """Compile the project."""
        source = local.path(self.source_of_primary)

        with local.cwd(source):
            verify_binaries(self)


class SklearnProjectETC(VProject):
    """
    Project to run an sklearn experiment: extra trees classifier - etc.
    """

    NAME = 'sklearn_experiment_etc'  # Estimator anpassen
    DOMAIN = ProjectDomains.HPC
    GROUP = 'python_projects'
    
    SOURCE = [
        PaperConfigSpecificGit(
            project_name=NAME,
            remote="https://github.com/lukasklein-dev/lk_bachelor_sklearn",
            local="lk_bachelor_sklearn",
            limit=None,
            refspec="origin/HEAD"),
        FeatureSource()
    ]

    WORKLOADS = {
        WorkloadSet(WorkloadCategory.MEDIUM): [
            VCommand(
                SourceRoot("lk_bachelor_sklearn") / RSBinary("case_study_MNIST"),
                "--estimator-etc", # Estimator anpassen
                ConfigParams(),
            )
        ]
    }

    @staticmethod
    def binaries_for_revision(
            revision: ShortCommitHash) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        binary_map = RevisionBinaryMap(get_local_project_repo(
            SklearnProjectETC.NAME)) # Estimator anpassen

        binary_map.specify_binary("case_study_MNIST", BinaryType.EXECUTABLE, override_entry_point="case_study_MNIST.py")

        return binary_map[revision]

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        """Compile the project."""
        source = local.path(self.source_of_primary)

        with local.cwd(source):
            verify_binaries(self)


class SklearnProjectGPC(VProject):
    """
    Project to run an sklearn experiment: gaussian process classifier - gpc.
    """

    NAME = 'sklearn_experiment_gpc'  # Estimator anpassen
    DOMAIN = ProjectDomains.HPC
    GROUP = 'python_projects'
    
    SOURCE = [
        PaperConfigSpecificGit(
            project_name=NAME,
            remote="https://github.com/lukasklein-dev/lk_bachelor_sklearn",
            local="lk_bachelor_sklearn",
            limit=None,
            refspec="origin/HEAD"),
        FeatureSource()
    ]

    WORKLOADS = {
        WorkloadSet(WorkloadCategory.MEDIUM): [
            VCommand(
                SourceRoot("lk_bachelor_sklearn") / RSBinary("case_study_MNIST"),
                "--estimator-gpc", # Estimator anpassen
                ConfigParams(),
            )
        ]
    }

    @staticmethod
    def binaries_for_revision(
            revision: ShortCommitHash) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        binary_map = RevisionBinaryMap(get_local_project_repo(
            SklearnProjectGPC.NAME)) # Estimator anpassen

        binary_map.specify_binary("case_study_MNIST", BinaryType.EXECUTABLE, override_entry_point="case_study_MNIST.py")

        return binary_map[revision]

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        """Compile the project."""
        source = local.path(self.source_of_primary)

        with local.cwd(source):
            verify_binaries(self)


class SklearnProjectGBC(VProject):
    """
    Project to run an sklearn experiment: gradient boosting classifier - gbc.
    """

    NAME = 'sklearn_experiment_gbc'  # Estimator anpassen
    DOMAIN = ProjectDomains.HPC
    GROUP = 'python_projects'
    
    SOURCE = [
        PaperConfigSpecificGit(
            project_name=NAME,
            remote="https://github.com/lukasklein-dev/lk_bachelor_sklearn",
            local="lk_bachelor_sklearn",
            limit=None,
            refspec="origin/HEAD"),
        FeatureSource()
    ]

    WORKLOADS = {
        WorkloadSet(WorkloadCategory.MEDIUM): [
            VCommand(
                SourceRoot("lk_bachelor_sklearn") / RSBinary("case_study_MNIST"),
                "--estimator-gbc", # Estimator anpassen
                ConfigParams(),
            )
        ]
    }

    @staticmethod
    def binaries_for_revision(
            revision: ShortCommitHash) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        binary_map = RevisionBinaryMap(get_local_project_repo(
            SklearnProjectGBC.NAME)) # Estimator anpassen

        binary_map.specify_binary("case_study_MNIST", BinaryType.EXECUTABLE, override_entry_point="case_study_MNIST.py")

        return binary_map[revision]

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        """Compile the project."""
        source = local.path(self.source_of_primary)

        with local.cwd(source):
            verify_binaries(self)


class SklearnProjectMNB(VProject):
    """
    Project to run an sklearn experiment: multinomial naive bayes classifier - mnb.
    """

    NAME = 'sklearn_experiment_mnb'  # Estimator anpassen
    DOMAIN = ProjectDomains.HPC
    GROUP = 'python_projects'
    
    SOURCE = [
        PaperConfigSpecificGit(
            project_name=NAME,
            remote="https://github.com/lukasklein-dev/lk_bachelor_sklearn",
            local="lk_bachelor_sklearn",
            limit=None,
            refspec="origin/HEAD"),
        FeatureSource()
    ]

    WORKLOADS = {
        WorkloadSet(WorkloadCategory.MEDIUM): [
            VCommand(
                SourceRoot("lk_bachelor_sklearn") / RSBinary("case_study_MNIST"),
                "--estimator-mnb", # Estimator anpassen
                ConfigParams(),
            )
        ]
    }

    @staticmethod
    def binaries_for_revision(
            revision: ShortCommitHash) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        binary_map = RevisionBinaryMap(get_local_project_repo(
            SklearnProjectMNB.NAME)) # Estimator anpassen

        binary_map.specify_binary("case_study_MNIST", BinaryType.EXECUTABLE, override_entry_point="case_study_MNIST.py")

        return binary_map[revision]

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        """Compile the project."""
        source = local.path(self.source_of_primary)

        with local.cwd(source):
            verify_binaries(self)