"""Small test project to run basic vara tests."""
import typing as tp

import benchbuild as bb
from plumbum import local

from varats.project.project_domain import ProjectDomains
from varats.project.project_util import ProjectBinaryWrapper
from varats.project.varats_project import VProject
from varats.utils.git_util import ShortCommitHash
from varats.project.project_util import (
    ProjectBinaryWrapper,
    BinaryType,
    get_local_project_repo,
    verify_binaries,
    RevisionBinaryMap,
)

from benchbuild.command import SourceRoot, WorkloadSet
from varats.experiment.workload_util import (
    RSBinary,
    WorkloadCategory,
    ConfigParams,
)
from varats.project.varats_command import VCommand
from varats.project.sources import FeatureSource


class SklearnLKBachelor(VProject):
    """
    Basic tests:

    Different small test files
    """

    NAME = 'sklearn_experiment'
    DOMAIN = ProjectDomains.TEST # TODO: was passt zu sklearn?
    GROUP = 'python_projects' # TODO: was passt zu sklearn?

    SOURCE = [
        bb.source.Git(
            remote="https://github.com/lukasklein-dev/lk-bachelor-sklearn",
            local="sklearn", # TODO
            limit=None,
            refspec="origin/HEAD"),
        FeatureSource()
    ]

    WORKLOADS = {
        WorkloadSet(WorkloadCategory.MEDIUM): [
            VCommand(
                SourceRoot("sklearn_experiment") / RSBinary("case_study_MNIST.py"),
                ConfigParams(),
                #ConfigParams("-z", "-k"),
                #requires_all_args={"-z", "-k"}
            )
        ]
    }

    # TODO Überprüfen ob ich jetzt binaries brauche. (Sebi)
    @staticmethod
    def binaries_for_revision(
            revision: ShortCommitHash) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        binary_map = RevisionBinaryMap(get_local_project_repo(
            SklearnLKBachelor.NAME))

        binary_map.specify_binary("case_study_MNIST.py", BinaryType.EXECUTABLE)

        return binary_map[revision]

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        """Compile the project."""
        source = local.path(self.source_of_primary)

        with local.cwd(source):
            verify_binaries(self)