"""Project to run an sklearn experiment as part of my bachelor's thesis."""
import typing as tp

import benchbuild as bb
from plumbum import local

from varats.utils.config import get_current_config_id

from varats.project.project_domain import ProjectDomains
from varats.paper.paper_config import PaperConfigSpecificGit
from varats.project.project_util import ProjectBinaryWrapper
from varats.project.varats_project import VProject
from varats.utils.git_util import ShortCommitHash
from varats.project.project_util import (
    ProjectBinaryWrapper,
    BinaryType,
    get_local_project_repo,
    verify_binaries,
    RevisionBinaryMap,
)

from benchbuild.command import SourceRoot, WorkloadSet
from varats.experiment.workload_util import (
    RSBinary,
    WorkloadCategory,
    ConfigParams,
)
from varats.project.varats_command import VCommand
from varats.project.sources import FeatureSource


class SklearnProjectDTCTest(VProject):
    """
    Project to run an sklearn experiment: decision tree classifier - dtc.
    """

    NAME = 'sklearn_experiment_dtc_test'  # Estimator anpassen
    DOMAIN = ProjectDomains.TEST
    GROUP = 'python_projects'
    
    SOURCE = [
        PaperConfigSpecificGit(
            project_name=NAME,
            remote="https://github.com/lukasklein-dev/lk_bachelor_sklearn",
            local="lk_bachelor_sklearn",
            limit=None,
            refspec="origin/HEAD"),
        FeatureSource()
    ]

    WORKLOADS = {
        WorkloadSet(WorkloadCategory.MEDIUM): [
            VCommand(
                SourceRoot("lk_bachelor_sklearn") / RSBinary("case_study_MNIST"),
                "--estimator-dtc", # Estimator anpassen
                ConfigParams(),
            )
        ]
    }

    @staticmethod
    def binaries_for_revision(
            revision: ShortCommitHash) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        binary_map = RevisionBinaryMap(get_local_project_repo(
            SklearnProjectDTCTest.NAME)) # Estimator anpassen

        binary_map.specify_binary("case_study_MNIST", BinaryType.EXECUTABLE, override_entry_point="case_study_MNIST.py")

        return binary_map[revision]

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        """Compile the project."""
        source = local.path(self.source_of_primary)

        with local.cwd(source):
            verify_binaries(self)


class SklearnProjectDTC(VProject):
    """
    Project to run an sklearn experiment: decision tree classifier - dtc.
    """

    NAME = 'sklearn_experiment_dtc'  # Estimator anpassen
    DOMAIN = ProjectDomains.TEST
    GROUP = 'python_projects'
    
    SOURCE = [
        PaperConfigSpecificGit(
            project_name=NAME,
            remote="https://github.com/lukasklein-dev/lk_bachelor_sklearn",
            local="lk_bachelor_sklearn",
            limit=None,
            refspec="origin/HEAD"),
        FeatureSource()
    ]

    WORKLOADS = {
        WorkloadSet(WorkloadCategory.MEDIUM): [
            VCommand(
                SourceRoot("lk_bachelor_sklearn") / RSBinary("case_study_MNIST"),
                "--estimator-dtc", # Estimator anpassen
                ConfigParams(),
            )
        ]
    }

    @staticmethod
    def binaries_for_revision(
            revision: ShortCommitHash) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        binary_map = RevisionBinaryMap(get_local_project_repo(
            SklearnProjectDTCTest.NAME)) # Estimator anpassen

        binary_map.specify_binary("case_study_MNIST", BinaryType.EXECUTABLE, override_entry_point="case_study_MNIST.py")

        return binary_map[revision]

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        """Compile the project."""
        source = local.path(self.source_of_primary)

        with local.cwd(source):
            verify_binaries(self)